export const ADD_DOG = 'ADD_DOG';
export const ADD_DOG_BASIC_INFO = 'ADD_DOG_BASIC_INFO';
export const EMPTY_NEW_DOG_OBJECT = 'EMPTY_NEW_DOG_OBJECT';
export const GET_DOG_DATA_FROM_DB = 'GET_DOG_DATA_FROM_DB';

export const FETCH_DOG_DATA_START = 'FETCH_DOG_DATA_START';
export const FETCH_DOG_DATA_SUCCESS = 'FETCH_DOG_DATA_SUCCESS';
export const FETCH_DOG_DATA_FAILED = 'FETCH_DOG_DATA_FAILED';
